name: ai_daging
description: "Proyek Flutter untuk AI Daging"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1
  camera: ^0.11.1
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0
  permission_handler: ^11.4.0
  image: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - assets/model/

  # Uncomment dan sesuaikan jika Anda ingin menambahkan font khusus
  # fonts:
  #   - family: NamaFont
  #     fonts:
  #       - asset: fonts/NamaFont-Regular.ttf
  #       - asset: fonts/NamaFont-Bold.ttf
  #         weight: 700